### ISSUE TITLE
where is 'wms-inventory'

### ISSUE THREAD

**Issue by bxter** [openwms/org.openwms.wms.receiving.lib#22]
![image](https://user-images.githubusercontent.com/59326851/211972363-d684aa11-edbb-4042-9610-7e72c3f2202a.png)

I can't find 'wms-inventory' service source code, where can find??

**Comment by openwms** [comment]
Hi @bxter and thank you for your analysis. That's in fact an issue. The `wms-inventory` is a remote service that may not be deployed in your project. I have implemented that service and use it in projects but thats at all not a requirement. Hence I've opened #23 for this and will fix this. This has a further impact on the other 2 inventory SPI as well and I'll open also issues for that.

**Comment by openwms** [comment]
Close this issue after resolving #23 #24
